package com.brins.baselib.module

/**
 * @author lipeilin
 * @date 2020/7/13
 */
val ITEM_BASE_MUSIC = 0

val ITEM_HOME_BANNER = 0x10
val ITEM_HOME_PERSONALIZED = 0x11
val ITEM_HOME_SINGLE_TITLE = 0x12
val ITEM_HOME_PERSONALIZED_MUSIC = 0x13
val ITEM_HOME_NEWEST_ALBUM = 0x14
val ITEM_HOME_NEWEST = 0x15
val ITEM_HOME_TOP_MUSIC = 0x17
val ITEM_HOME_MUSIC_LIST= 0x19
val ITEM_HOME_SINGLE_TITLE_MORE = 0x20
val ITEM_HOME_TOP_RECOMMEND = 0X21
val ITEM_HOME_MUSIC_LIST_INTELLIGENCE = 0X30


val ITEM_BASE_PLAYLIST = 0x16
val ITEM_MUSIC_LIST_TRACK_MUSIC = 0x18

val ITEM_MUSIC_DETAIL_COMMENT = 0X22

val ITEM_BANNER_MUSIC = 0X23

val ITEM_ALBUM_LIST_MUSIC = 0X24

val ITEM_MINE_UNLOGIN = 0X25
val ITEM_MINE_LIKE = 0X26
val ITEM_MINE_RECENTLY_MUSIC = 0X27
val ITEM_MINE_MUSIC_LIST = 0X28
val ITEM_MINE_RECOMMEND_MUSIC_LIST = 0X29
val ITEM_MINE_SINGLE_TITLE = 0x37
val ITEM_MINE_EVENT_DATA = 0x38

val ITEM_DAILY_MUSIC = 0X21

val ITEM_SEARCH_HOT = 0X31
val ITEM_SEARCH_MUSIC_VIDEO = 0X32
val ITEM_SEARCH_USER = 0X33
val ITEM_SEARCH_DJRADIO = 0X34
val ITEM_SEARCH_ALBUM = 0X35
val ITEM_SEARCH_ARTIST = 0X36
val ITEM_SEARCH_MUSIC_LIST= 0X21

val ITEM_FIND_FOLLOW = 0X39
val ITEM_FIND_SINGLE_TITLE = 0x12

val ITEM_VIDEO_MUSIC_VIDEO = 0x12
val ITEM_VIDEO_MUSIC_VIDEO_COMMENT = 0x13

val ITEM_RADIO_SINGLE_TITLE = 0x12
val ITEM_RADIO_RECOMMEND_DATA = 0x13
val ITEM_RADIO_PROGRAM_DATA = 0x14








