package com.brins.baselib.module

/**
 * @author lipeilin
 * @date 2020/7/13
 */

val ITEM_HOME_BANNER = 0x10
val ITEM_HOME_PERSONALIZED = 0x11
val ITEM_HOME_SINGLE_TITLE = 0x12
val ITEM_HOME_PERSONALIZED_MUSIC = 0x13
val ITEM_HOME_NEWEST_ALBUM = 0x14
val ITEM_HOME_NEWEST = 0x15
val ITEM_HOME_TOP_MUSIC = 0x17
val ITEM_HOME_MUSIC_LIST= 0x19
val ITEM_HOME_SINGLE_TITLE_MORE = 0x20
val ITEM_HOME_TOP_RECOMMEND = 0X21

val ITEM_BASE_PLAYLIST = 0x16
val ITEM_MUSIC_LIST_TRACK_MUSIC = 0x18

val ITEM_MUSIC_DETAIL_COMMENT = 0X22

val ITEM_BANNER_MUSIC = 0X23

val ITEM_ALBUM_LIST_MUSIC = 0X24

